server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://192.168.1.111:3306/heima?useSSL=false
    username: root
    password: guwenjie03116
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.111
    port: 5672
    username: Gu
    password: 123
    virtual-host: /
  application:
    name: EsServer
  cloud:
    nacos:
      server-addr: 192.168.1.111:10086 # nacos地址
logging:
  level:
    com.Gu: debug
  pattern:
    dateformat: HH:mm:ss:SSS
