server:
  port: 8083
spring:
  rabbitmq:
    host: 82.157.249.61
    port: 5672
    username: Gu
    password: 123
    virtual-host: /
  application:
    name: EsServer
  cloud:
    nacos:
      server-addr: 43.140.192.126:8848 # nacos地址
logging:
  level:
    com.Gu: debug
  pattern:
    dateformat: HH:mm:ss:SSS
