server:
  port: 8084
spring:
  rabbitmq:
    host: 10.31.75.228
    port: 5672
    username: Gu
    password: 123
    virtual-host: /
  application:
    name: EsServer
  cloud:
    nacos:
      server-addr: 10.31.75.228:10086 # nacos地址
logging:
  level:
    com.Gu: debug
  pattern:
    dateformat: HH:mm:ss:SSS
