server:
  port: 10010
logging:
  level:
    com.Gu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.1.111:10086 # nacos地址

