server:
  port: 8083
logging:
  level:
    com.Gu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: tokenserver
  cloud:
    nacos:
      server-addr: 10.31.75.228:10086 # nacos地址

