server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-inuh51r0.sql.tencentcdb.com:29029/meeting?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: GoFQT7Ss#S$PCr7l7)^L~fva_Kg09K@QVV_
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 120000
  application:
    name: userserver
  rabbitmq:
    host: 82.157.249.61
    port: 5672
    username: Gu
    password: 123
    virtual-host: /
  cloud:
    nacos:
      server-addr: 43.140.192.126:8848 # nacos服务地址

    sentinel:
      transport:
        dashboard: 43.140.192.126:8080
      web-context-unify: false #关闭context整合,sentinel默认会给进入SpringMVC的所有请求设置同一个root资源，会导致链路模式失效。

mybatis:
  type-aliases-package: com.Gu.user.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*Mapper.xml
logging:
  level:
    com.Gu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  sentinel:
    enabled: true