server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://47.104.19.189:3306/meeting?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: guwenjie03116
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: userserver
  cloud:
    nacos:
      server-addr: 47.104.19.189:10086 # nacos服务地址
    sentinel:
      transport:
        dashboard: localhost:8848
      web-context-unify: false #关闭context整合,sentinel默认会给进入SpringMVC的所有请求设置同一个root资源，会导致链路模式失效。
mybatis:
  type-aliases-package: com.Gu.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*Mapper.xml
logging:
  level:
    com.Gu: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


feign:
  httpclient:
    enabled: true # 支持HttpClient的开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 50 # 单个路径的最大连接数
  sentinel:
    enabled: true